# Generated by Django 3.1.2 on 2020-11-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201113_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='show',
        ),
    ]
